[package]
name = "lok"
version = "0.0.1"
authors = ["wyhaya <wyhaya@gmail.com>"]
edition = "2018"
description = "Calculation code information"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/wyhaya/lok"
repository = "https://github.com/wyhaya/lok.git"


[dependencies]
ace = "0.0.2"
deque = "0.3.2"
num_cpus = "1.10.1"
regex = "1.1.7"
lazy_static = "1.3.0"