version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: codecov
          command: ./node_modules/.bin/codecov
      - run:
          name: build
          command: yarn build
      - run:
          name: bin
          command: cd ./dist/ && chmod 777 ./bin/index.js && ./bin/index.js